NAIVE BAYES klasifikasi kualitas susu

kelas: PSTI-C
- 2215061015    | Arnora Mardiansyah
- 2215061059    | Laurentius Nicholas Christmarines
- 2255061004    | Theofani Hati Kusumawardani

TAHAP PERSIAPAN DATASET

In [3]:
import numpy as py
import pandas as pd

dataset = pd.read_excel('milk_grading.xlsx')
dataset.head()

pH  Temperature  Taste  Odor  Fat   Turbidity  Colour Grade
0  6.6           35      1     0     1          0     254  high
1  6.6           36      0     1     0          1     253  high
2  8.5           70      1     1     1          1     246   low
3  9.5           34      1     1     0          1     255   low
4  6.6           37      0     0     0          0     255  high

In [4]:
print("apakah ada data kosong? " + str(dataset.empty))

apakah ada data kosong? False


In [5]:
from sklearn.preprocessing import LabelEncoder                                  # ubah 'high' dan 'low' di kolom Grade jadi biner 1/0
en = LabelEncoder()

dataset['Grade'] = en.fit_transform(dataset['Grade'])
dataset.head()

pH  Temperature  Taste  Odor  Fat   Turbidity  Colour  Grade
0  6.6           35      1     0     1          0     254      0
1  6.6           36      0     1     0          1     253      0
2  8.5           70      1     1     1          1     246      1
3  9.5           34      1     1     0          1     255      1
4  6.6           37      0     0     0          0     255      0

In [6]:
X = dataset.iloc[:, :-1].values                                                 # deklar features sebagai semua kolom kecuali paling kanan
y = dataset.iloc[:, -1].values                                                  # deklar label sebagai kolom paling kanan

In [13]:
X

array([[  6.6,  35. ,   1. , ...,   1. ,   0. , 254. ],
       [  6.6,  36. ,   0. , ...,   0. ,   1. , 253. ],
       [  8.5,  70. ,   1. , ...,   1. ,   1. , 246. ],
       ...,
       [  3. ,  40. ,   1. , ...,   1. ,   1. , 255. ],
       [  6.8,  43. ,   1. , ...,   1. ,   0. , 250. ],
       [  8.6,  55. ,   0. , ...,   1. ,   1. , 255. ]])

In [14]:
y

array([0, 0, 1, ..., 1, 0, 1])

TAHAP PEMBAGIAN DATASET menjadi TESTING dan TRAINING

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.2,              # 20% sebagai testing dataset, 80% sebagai training dataset
                                                    random_state=0)

print(f'X_train shape{X_train.shape}')
print(f'X_test shape{X_test.shape}')

X_train shape(847, 7)
X_test shape(212, 7)


In [8]:
from sklearn.preprocessing import StandardScaler                                # scaling value di xlsx agar skala ga terlalu jauh
sc = StandardScaler()

X_train= sc.fit_transform(X_train)
X_test= sc.transform(X_test)

KLASIFIKASI data dengan NAIVE BAYES

In [15]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)                                                  #prediksi X_test ditampung dalam y_pred
y_pred                                                                          #tampilkan hasil prediksi

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0])

In [16]:
model.predict_proba(X_test)                                                     #probabilitas model yang dihasilkan

array([[9.29028485e-001, 7.09715153e-002],
       [1.77218051e-075, 1.00000000e+000],
       [9.01413960e-001, 9.85860401e-002],
       [2.01288005e-016, 1.00000000e+000],
       [9.60183322e-001, 3.98166784e-002],
       [9.71251543e-001, 2.87484569e-002],
       [5.31603051e-018, 1.00000000e+000],
       [7.75256100e-001, 2.24743900e-001],
       [9.29028485e-001, 7.09715153e-002],
       [9.98688786e-001, 1.31121397e-003],
       [2.06902550e-182, 1.00000000e+000],
       [9.60183322e-001, 3.98166784e-002],
       [9.99822398e-001, 1.77602258e-004],
       [9.96689691e-001, 3.31030923e-003],
       [8.89229424e-001, 1.10770576e-001],
       [9.67744297e-001, 3.22557032e-002],
       [9.93047761e-001, 6.95223892e-003],
       [9.93047761e-001, 6.95223892e-003],
       [9.36479102e-001, 6.35208978e-002],
       [3.80401959e-051, 1.00000000e+000],
       [7.75256100e-001, 2.24743900e-001],
       [2.50396824e-063, 1.00000000e+000],
       [9.94094466e-001, 5.90553443e-003],
       [7.7

TAHAP EVALUASI HASIL

In [11]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)                                           #bandingkan hasil prediksi dengan yang sebenarnya
print("confusion matrix: " + str(cm))                                           #bisa dilihat data yang terprediksi secara benar dan salah diprediksi

confusion matrix: [[143   0]
 [  7  62]]


In [12]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
print("akurasi 1= \n" + str(classification_report(y_test, y_pred)))             #lihat akurasi LENGKAP
print("akurasi 2= " + str(accuracy_score(y_test, y_pred)*100) + "%")            #ukur nilai akurasi klasifikasi naive bayes TANPA pembulatan
print("akurasi 3= " + str(round(accuracy_score(y_test, y_pred),2)*100) + "%")   #ukur nilai akurasi klasifikasi naive bayes DENGAN pembulatan
print("akurasi 4= " + str(model.score(X_test, y_test)*100) + "%")               #cara lain ukur akurasi

akurasi 1= 
              precision    recall  f1-score   support

           0       0.95      1.00      0.98       143
           1       1.00      0.90      0.95        69

    accuracy                           0.97       212
   macro avg       0.98      0.95      0.96       212
weighted avg       0.97      0.97      0.97       212

akurasi 2= 96.69811320754717%
akurasi 3= 97.0%
akurasi 4= 96.69811320754717%
